# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none
pr: none

pool: 
  vmImage: 'windows-latest'

resources:
  pipelines:
  - pipeline: hrx-seo-automation
    project: HealthRX website
    source: hrx-seo-automation
    trigger: true

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# - script: |
#     npm install
#   displayName: 'npm install'

# - script: 
#     npm run test
#   displayName: 'run all tests'



